# Generated by Django 2.0.5 on 2018-05-31 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateTimeField(verbose_name='Date project started')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.Activity')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.Category')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.Category'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.Project'),
        ),
    ]
