# Generated by Django 2.0.5 on 2018-05-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Project'),
        ),
    ]
