# Generated by Django 2.0.5 on 2018-05-31 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_auto_20180531_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='time_tracker.Project'),
        ),
    ]
